# Generated by Django 5.0 on 2025-12-06 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='api.course'),
        ),
        migrations.AddField(
            model_name='exam',
            name='custom_course',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exam',
            name='custom_department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exam',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='api.department'),
        ),
    ]
